### PR TITLE
Mom eqn upwind

### PR DESCRIPTION
**Pull request by davelee2804**
Not ready for review, just open for discussion. Still playing with different formulations to try and get a method for damping vertical oscillations.

### CODE REVIEW

**Comment by davelee2804** [comment]
Added in a continuous interior penalty term in `F_u_damp!()` which successfully suppresses the oscillations

**Comment by davelee2804** [comment]
There is still a little bit of velocity checkerboarding, which may be due to the computational mode, but things are much improved (see vorticity, velocity magnitude and theta plots attached)
theta_final
u_mag_final
vort_final

**Comment by amartinhuertas** [comment]
> There is still a little bit of velocity checkerboarding, which may be due to the computational mode, but things are much improved (see vorticity, velocity magnitude and theta plots attached)

(1) Do you have any other code to compare against?  (2) have to tried to play with stabilization parameters?

**Comment by amartinhuertas** [comment]
(3) have you tried larger resolution?

**Comment by davelee2804** [comment]
1) We have the standard Robert rising bubble test case (Test case 3, fig 5 of this paper): https://www.sciencedirect.com/science/article/abs/pii/S0021999107005384
Bubble looks to be rising correctly, but without more resolution it is hard to say...
2) Yes, with a factor 1/4 less there was no noticible effect from the parameter
3) Would like to, but this is the maximum resolution I can run on 192GB of a Gadi node

**Comment by amartinhuertas** [comment]
> Would like to, but this is the maximum resolution I can run on 192GB of a Gadi node

Have you tried to run the code with Julia 1.8?

**Comment by davelee2804** [comment]
No, not yet sorry. I've been busy trying to get the stabilisation working. I will do so now...

**Comment by amartinhuertas** [comment]
> No, not yet sorry. I've been busy trying to get the stabilisation working. I will do so now...

I would give it a try, to see if that improves things (perhaps not). I am far from knowing which might be the source of the memory consumption issue. Julia is a GCed language, it should not leak memory with time, and it is precisely what seems to be hapenning ...

**Comment by davelee2804** [comment]
...getting an error with 1.8.5 as:
```
 [3] require(into::ArgumentError: Package Distances does not have SparseArrays in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have Distances checked out for development and have
  added SparseArrays as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Distances
```
I've tried running `] instantiate; ]resolve` but it doesn't seem to have fixed the issue

**Comment by amartinhuertas** [comment]
I would remove the Project.toml and Manifest.toml and start from scratch

**Comment by amartinhuertas** [comment]
the only caveat is that you need to add a very particular version of GridapSolvers, namely:

```
> pkg> add https://github.com/gridap/GridapSolvers.jl#solve_ambiguity_when_no_precon_is_used
```

from the Julia package manager

**Comment by davelee2804** [comment]
Thanks, I think I've broken my entire env, but that's OK, I'll take a look later...

**Review by amartinhuertas — APPROVED** [review]

**Pull request merged**
